import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CURD-FLASK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className="bg-gray-900 text-white ">
        <Navbar/>
        <div className="container mx-auto min-h-screen">
        {children}
        </div>
        <Footer/>
        </body>
    </html>
  );
}
